apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paf-assignment-keycloak-db-pvc
  namespace: paf-assignment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

