apiVersion: v1
kind: Secret
metadata:
  name: paf-assignment-secret
  namespace: paf-assignment
data:
  DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcGFmLWFzc2lnbm1lbnQtZGItc2VydmljZTo1NDMyL3BhZg==
  DATASOURCE_USENAME: cGFm
  DARASOURCE_PASSWORD: cGFm
  AUTH_CLIENT_ID: cGFmLWV4ZXJjaXNlLWNsaWVudA==
  AUTH_CLIENT_SECRET: czNjcjN0
  AUTH_ISSUER_URI: aHR0cHM6Ly9wYWYtYXNzaWdubWVudC5rZXljbG9hay50b3BhbGlkaXMub25saW5lL3JlYWxtcy9wYWYtZXhlcmNpc2U=
  AUTH_ADMIN_ROLE_NAME: cGFmLWV4ZXJjaXNlLWFkbWlu
  AUTH_PAF_SESSION_COOKIE_NAME: UEFGU0VTU0lPTg==
  AUTH_TOKEN_ISSUANCE_URI: L3Byb3RvY29sL29wZW5pZC1jb25uZWN0L3Rva2Vu
  AUTH_LOGOUT_URI: L3Byb3RvY29sL29wZW5pZC1jb25uZWN0L2xvZ291dA==
  AUTH_INTROSPECT_URI: L3Byb3RvY29sL29wZW5pZC1jb25uZWN0L3Rva2VuL2ludHJvc3BlY3Q=
  AUTH_USER_ID_HEADER_NAME: eC11c2VyLWlk
  AUTH_IS_ADMIN_HEADER_NAME: eC1pcy1hZG1pbg==
  AUTH_SECURED_PATHS: YXBp