apiVersion: v1
kind: Secret
metadata:
  name: paf-assignment-keycloak-db-secret
  namespace: paf-assignment
data:
  POSTGRES_DB: a2V5Y2xvYWs=
  POSTGRES_USER: a2V5Y2xvYWs=
  POSTGRES_PASSWORD: a2V5Y2xvYWs=
  HOSTNAME: Y2VjbG91ZHYyLWtleWNsb2FrLWRiLXNlcnZpY2U=
  PORT: NTQzMg==
  DB: a2V5Y2xvYWs=
  USERNAME: a2V5Y2xvYWs=
  PASSWORD: a2V5Y2xvYWs=
  S3_KEY_ID: RE8wMEYzTEdVUFlMUjNXODlOTjg=
  S3_SECRET: WDY3NXRlWm12S3RNSUxjcGg4WFIxc0hHMU11T2RRbFVld0ZBY1UyODQydw==
  S3_BUCKET: Y2UtY2xvdWQtczM=
  DEPLOYMENT_ENV: REVW
  S3_ENDPOINT: aHR0cHM6Ly9ueWMzLmRpZ2l0YWxvY2VhbnNwYWNlcy5jb20=
  BACKUP_TYPE: a2V5Y2xvYWs=

